### ISSUE TITLE
points position at MODIS tile

### ISSUE THREAD

**Issue by kongdd** [zhangyaonju/batch_site_retrieval_from_global_MODIS_product#1]
Hi Yao, 

- Any reference of modis tile 'h' & 'v' [calculation](https://github.com/zhangyaonju/batch_site_retrieval_from_global_MODIS_product/blob/9a9d11f51a00940fa347d1ee8a0596b72261bba7/get_time_series_mod09a1_product.R#L20)?

 - For 1km MODIS product, do you have any suggestion to modify this script?

Dongdong
Regards

**Comment by kongdd** [comment]
This will be a very practical function. Do you think whether this function is correct?

```r
#' Get points data from MODIS tiles
#' 
#' @param coor 2-column matrix of coordinates (longitude, latitude)
#' @param cellsize 500m products, cellsize is regarded as 1/240; 1km product, 
#' cellsize is regarded as 1/120.
#' 
#' @return 
#' \itemize{
#' \item{h} MODIS tile horizontal id
#' \item{v} MODIS tile vertical id
#' \item{i} point horizontal position at the tile
#' \item{j} point vertical position at the tile
#' }
#' @references 
#' https://landweb.modaps.eosdis.nasa.gov/cgi-bin/developer/tilemap.cgi
#' 
#' @export
#' @importFrom data.table data.table
getPointsMODISTile <- function(coor, cellsize = 1/240){
    scale    <- 463.312716528 *cellsize*240 # meter; 1km: 926.625433055833
    nline    <- 1/cellsize*10               # how many lines per tile?

    proj_sin <- "+proj=sinu +lon_0=0 +x_0=0 +y_0=0 +a=6371007.181 +b=6371007.181 +units=m +no_defs"

    # coor: coordinate matrix, (longitude, latitude)
    sin_xy <- project(coor, proj)
    sin_ij <- sin_xy/scale
    
    h <- floor(sin_ij[, 1]/nline) + 18
    v <- 8 - floor(sin_ij[, 2]/nline)
    # calculate the tile and its location
    px <- cbind( ceiling(sin_ij[, 1] %% nline),          # horizontal
                 ceiling(nline - sin_ij[, 2] %% nline)) %>% 
        set_colnames(sprintf("s%d_%s", ceiling(scale/1e2)*1e2, c("i", "j")))# vertical

    data.table(coor, h, v, px)#return    
}
```

**Comment by zhangyaonju** [comment]
Hi Dongdong,

the MODIS tile is usually 5 degree by 5 degree for 500m or 1km dataset based on the Sinusoidal Projection. I do not understand the cell size parameter you used.
For MODIS product, you can now use python interface and directly extract coordinates from google earth engine. see https://github.com/khufkens/gee_subset

hope that helps.

Yao

**Comment by kongdd** [comment]
In GEE, the resolution of 500m MODIS product is 86400*43200. So I treat the cellsize of 500m product as 1/240. Extract data in GEE is simple and easy. But the data set is quite limited.

I need to extract BESS model GPP & ET product (MODIS projection, 1km product). I have to process in local computer. 

I just need to know how to calculate 'h' & 'v', and position 'i' & 'j'. 

I have validated the function `getPointsMODISTile`. The result is exactly as [ MODIS official site](https://landweb.modaps.eosdis.nasa.gov/cgi-bin/developer/tilemap.cgi). But I don't know the behind reason.

**Comment by zhangyaonju** [comment]
The function you used seems correct, I thought you know how to do it.
if you look at each tile of the sinusoidal projection, you will find the extent (xmax,xmin,ymax,ymin), it is in the unit of meters after you project the longitude/latitude to sinusoidal projection. the center (0deg long, 0deg latitude) also corresponds to (0, 0) meter in sinusoidal. based on the extent of each tile and the projected latlong coordinates in sinusoidal, you can get the tile number and its position.

let me know if you do not understand what I said.

**Comment by kongdd** [comment]
Thanks for your patient explanation! Quite clear now.

By the way, have to point that 2400*2400 is 10deg*10deg for 500m MODIS product. see [MODIS tile](https://modis-land.gsfc.nasa.gov/MODLAND_grid.html) for detail.

**Comment by zhangyaonju** [comment]
Yes, you are correct. I did not check when I answer that question.
